// <auto-generated />

using Employee.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Employee.Infrastructure.Migrations
{
	[DbContext(typeof(EmployeeDbContext))]
	partial class EmployeeDbContextModelSnapshot : ModelSnapshot
	{
		protected override void BuildModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.UseIdentityColumns()
				.HasAnnotation("Relational:MaxIdentifierLength", 128)
				.HasAnnotation("ProductVersion", "5.0.1");

			modelBuilder.Entity("Employee.Domain.Employee", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasColumnType("int")
					.UseIdentityColumn();

				b.Property<int>("DepartmentId")
					.HasColumnType("int");

				b.Property<string>("Name")
					.HasColumnType("nvarchar(max)");

				b.HasKey("Id");

				b.ToTable("Employees");
			});
#pragma warning restore 612, 618
		}
	}
}